project:
  type: website

website:
  title: "my_Oslofjord_site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: map.qmd
        text: Kart

format:
  html:
    theme: default
    css: styles.css
  

