project:
  type: website

website:
  title: "Oslofjorden WebMap"
  navbar:
    left:
      - href: index.qmd
        text: "Global natur"
      - href: pages/Oslofjord.qmd
        text: "Oslofjorden"
      - href: pages/kommunekart.qmd
        text: "Kommunekart"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false